#ifndef	SPI_FLASH_APP_H
#define	SPI_FLASH_APP_H

#include "stm32f10x.h"

#define	FLASH_ONE_SECTOR_BYTES										4096

#define FLASH_CHIP_START_SECTOR           				0


#define	FLASH_GB2312_16_START_SECTOR							0
#define FLASH_GB2312_16_END_SECTOR								66
#define	FLASH_HZK16_END_SECTOR						FLASH_GB2312_16_END_SECTOR
#define	FLASH_HZK16_END_ADDR							(FLASH_HZK16_END_SECTOR*FLASH_ONE_SECTOR_BYTES)

#define	FLASH_UPDATE_START_SECTOR									67
#define FLASH_UPDATE_END_SECTOR										223

#define FLASH_VDR_DATA_SPEED_START_SECTOR					588
#define FLASH_VDR_DATA_SPEED_END_SECTOR						692

#define FLASH_VDR_DATA_POSITION_START_SECTOR			693
#define FLASH_VDR_DATA_POSITION_END_SECTOR				755

#define FLASH_VDR_DATA_DOUBT_START_SECTOR					865
#define FLASH_VDR_DATA_DOUBT_END_SECTOR						875

#define FLASH_VDR_DATA_OVER_TIME_START_SECTOR			876
#define FLASH_VDR_DATA_OVER_TIME_END_SECTOR				880

#define FLASH_VDR_DATA_DRIVER_START_SECTOR				881
#define FLASH_VDR_DATA_DRIVER_END_SECTOR					885

#define FLASH_VDR_DATA_POWER_START_SECTOR					886
#define FLASH_VDR_DATA_POWER_END_SECTOR						889

#define FLASH_VDR_DATA_PARAMETER_START_SECTOR			890
#define FLASH_VDR_DATA_PARAMETER_END_SECTOR				893

#define FLASH_VDR_DATA_SPEED_STATUS_START_SECTOR	894
#define FLASH_VDR_DATA_SPEED_STATUS_END_SECTOR		897

#define	FLASH_VDR_STATUS_SET_SECTOR								898

#define	FLASH_VDR_OVERTIME_START_SECTOR						965//用于保存超时驾驶的驾驶员信息，保存的内容见结构体VDR_OVERTIME_DRIVER_STRUCT
#define	FLASH_VDR_OVERTIME_START_ADDR		(FLASH_VDR_OVERTIME_START_SECTOR*FLASH_ONE_SECTOR_BYTES)
#define	FLASH_VDR_OVERTIME_END_SECTOR							966



#define	FLASH_VDR_POSITION_START_SECOTR						1021
#define	FLASH_VDR_POSITION_END_SECOTR							1022

#define FLASH_CHIP_END_SECTOR           					1023

ErrorStatus FLASH_CheckChip(void);

#endif
